### ISSUE TITLE
The translation of Aseprite has been migrated to Weblate.

### ISSUE THREAD

**Issue by TakWolf** [FabianoIlCapo/aseprite_italian#11]
Hi!

The translation of Aseprite has been migrated to Weblate.

Italian is here: https://hosted.weblate.org/projects/aseprite/aseprite/it/

The latest node has been imported.

The migration work has just begin, and when the workflow is completed, the copyright line will be retained.

Please feel free to try.
If any problem, please feel free to provide feedback at any time

**Comment by TakWolf** [comment]
We need the aseprite official to do this

**Comment by Flaconia** [comment]
> Hi!
> 
> The translation of Aseprite has been migrated to Weblate.
> 
> Italian is here: https://hosted.weblate.org/projects/aseprite/aseprite/it/
> 
> The latest node has been imported.
> 
> The migration work has just begin, and when the workflow is completed, the copyright line will be retained.
> 
> Please feel free to try. If any problem, please feel free to provide feedback at any time

Hi, thanks for keeping me up to date.
By opening the link you provided I see the Italian section of the Aseprite translation, but it says there are no translated strings at all. It's like it needs to be translated from scratch.
Can you please take a look? I suppose the idea was to import the existing translation.
Thank you

**Comment by TakWolf** [comment]
Yes, just here use the latest it.ini, I have helped organize the format

<img width="698" alt="image" src="https://github.com/FabianoIlCapo/aseprite_italian/assets/6064962/83457427-5cfe-417f-8b51-5b8dba7b9b10">

<img width="769" alt="image" src="https://github.com/FabianoIlCapo/aseprite_italian/assets/6064962/a1efe287-4a59-4808-845b-1b4766170beb">


Submission requires you to personally complete it, which will retain your contribution!!

Weblate is a better solution that is very easy to use.

If you have any difficulties, you can communicate at any time!!

**Comment by TakWolf** [comment]
It seems that there hasn't been a complete success.


You can try these two options

<img width="450" alt="image" src="https://github.com/FabianoIlCapo/aseprite_italian/assets/6064962/597e0c77-4877-4ad7-afb4-62f9fcf57d62">

**Comment by Flaconia** [comment]
Wait maybe the problem is that I'm uploading an older version of it.ini, let me double check if it's up to date with your repo

**Comment by TakWolf** [comment]
It seems like everything is going well. 

'deleting_tilemaps_will_delete_tilesets' -> This key translation may have issues, it should be 'tilemap' not 'layer'

Besides, there shouldn't be any other issues with me.



You can try whatever you want and anything can be rolled back.

**Comment by Flaconia** [comment]
Awesome, yep it was an old file I was trying to upload. Thank you so much for your help.
I'll have to get used to Weblate but I like how clean it is.
I'd just like a view where I have 2 columns: source language on the left and destination on the right, instead of both stacked one on top of the other like the Zen mode...



> 'deleting_tilemaps_will_delete_tilesets' -> This key translation may have issues, it should be 'tilemap' not 'layer'
> 
> Besides, there shouldn't be any other issues with me.
> 
> You can try whatever you want and anything can be rolled back.

I'll check this out and correct it.

By the way, where is the best place to contact you now that we're not going to use GitHub anymore?

**Comment by TakWolf** [comment]
Attention, I am not an official.  Any issues about aseprite should be submited to https://github.com/aseprite/  or  https://community.aseprite.org/

But you can communicate with me anytime! Anything, not limited to Aseprite

through email (You should have a contact record),
https://github.com/TakWolf/TakWolf/issues
[My persion discord](https://discord.gg/9HY9WD4TRe)

Even, you can keep the current repository and @ me!

All are welcome! Don't have any concerns!

**Comment by Flaconia** [comment]
@TakWolf  oh yes, I know you're not part of Aseprite's team. Just asking because you seem a good contact to have, you're very helpful.
I'll move to the Aseprite GitHub now, I currently don't know how normal Asperite users can download the latest transaltions.
See you there
